#! /bin/sh

bspc config window_gap                  0
bspc config border_width                3
bspc config click_to_focus              'button1'
bspc config focused_border_color        '#546E7A'
bspc config normal_border_color         '#1C1C1C'
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc monitor -d 'ZSH' 'Web' 'Media' 'General'
bspc desktop -l 'monocle'
bspc desktop -f '^3'

bspc rule -a URxvt                              desktop='^1' follow=on
bspc rule -a Google-chrome                      desktop='^2' follow=on
bspc rule -a Audacity				desktop='^3' follow=on
bspc rule -a Bluetooth-sendto			desktop='^3' follow=on
bspc rule -a Gimp				desktop='^3' follow=on
bspc rule -a Gummi				desktop='^3' follow=on
bspc rule -a Sxiv				desktop='^3' follow=on
bspc rule -a Zathura				desktop='^3' follow=on state=tiled
bspc rule -a feh				desktop='^3' follow=on
bspc rule -a kdenlive				desktop='^3' follow=on
bspc rule -a mpv				desktop='^3' follow=on
bspc rule -a mtp-ng-qt				desktop='^3' follow=on
bspc rule -a transmission			desktop='^3' follow=on
bspc rule -a Codeblocks				desktop='^4' follow=on
bspc rule -a Lxappearance			desktop='^4' follow=on
bspc rule -a Pavucontrol			desktop='^4' follow=on
bspc rule -a Simple-scan			desktop='^4' follow=on 
bspc rule -a System-config-printer.py		desktop='^4' follow=on
bspc rule -a Steam                              desktop='^4' follow=on
bspc rule -a VirtualBox				desktop='^4' follow=on
bspc rule -a Vncviewer                          desktop='^4' follow=on center=true
bspc rule -a Wine				desktop='^4' follow=on
bspc rule -a XCalc                              desktop='^4' follow=on state=floating
bspc rule -a jetbrains-pycharm-ce		desktop='^4' follow=on

panel &
kdeinit5
