#! /bin/sh

kill_daemons() {
    pkill mpd
    pkill bspc
    pkill panel
    pkill conky
    pkill udevil
    pkill --signal HUP transmission-daemon
    killall urxvt
    killall chrome
}

trap "trap - TERM; kill_daemons; kill 0" INT TERM HUP QUIT EXIT

dunst &
redshift &
lxpolkit &
mpd --no-daemon &
devmon --no-gui &
autocutsel -selection PRIMARY &
autocutsel -selection CLIPBOARD &
xautolock -time 25 -locker sleep_locker &
transmission-daemon --paused --foreground &
/usr/lib/bluetooth/obexd -a -r "$HOME"/Public &

wait
