#! /bin/sh

restart_panel() { 
    background_set -d
    pkill panel
    panel &
}
if pgrep Xorg &> /dev/null; then
    if xrandr | grep -o "HDMI-1 connected" &> /dev/null; then
        xrandr --output HDMI-1 --right-of eDP-1 --preferred --output eDP-1 --primary --preferred
        bspc monitor HDMI-1 -d 'HDMI-1'
        restart_panel
    else
        bspc monitor HDMI-1 -r &> /dev/null
        xrandr --output HDMI-1 --off
        restart_panel
    fi
fi
